"""Quiz, Question and Attempt tables

Revision ID: 43a05ed1072f
Revises: 87a95921d457
Create Date: 2020-03-04 00:03:12.087824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a05ed1072f'
down_revision = '87a95921d457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_quiz_created_by'), 'quiz', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_created_on'), 'quiz', ['created_on'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_quiz_id'), 'attempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_attempt_user_id'), 'attempt', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('ques_type', sa.Integer(), nullable=False),
    sa.Column('ques_json', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=64), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_attempt_user_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_quiz_id'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_quiz_created_on'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_created_by'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
